---
title: "final_project_1"
author: "Joanna Wright"
date: "1/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rio)
library(here)
library(janitor)
library(maps)
library(mapdata)

```

```{r loading the data}

d <- import(here("data", "ka_2018-19_lookback_report.xlsx")) %>%
  clean_names()

counties <- map_data("county")
or_county <- subset(counties, region == "oregon")

```


```{r cleaning the data}

d1 <- d %>%
  rename(county = oregon_kindergarten_assessment,
         district_id = x2,
         district = x3,
         inst_id = x4,
         inst_name = x5,
         inst_type = x6,
         stu_grp_type = x7,
         stu_grp = x8,
         avg_self_reg = x9) %>%
  select(c(1:9))

d1 <- d1 %>%
  filter(avg_self_reg != "*")

# need to double check online what the * means and make sure it's ok to remove. it removed a lot of rows!! 

d1 = d1[-1,]

```


```{r identifying keys, joining with map data}

d %>%
  count(oregon_kindergarten_assessment, x2, x3, x4, x5, x6, x7, x8) %>%
  filter(n>1)
# This shows we need all first 9 variables as the key.

or_county %>%
  count(order) %>%
  filter(n>1)
# the key in or_county is order 

# I chose to subset the d1 dataset in order to have a singular key (county), so that I can then do a one-to-many join with or_county. 
# (To do so, I first needed to convert the avg_self_reg variable to numeric and calculate the mean for county groups.) 

str(d1)
d1$avg_self_reg = as.numeric(d1$avg_self_reg)

d2 <- d1 %>%
  group_by(county) %>%
  summarise(avg_self_reg_county = mean(avg_self_reg))

or_county <- or_county %>%
  rename(county = subregion)

d2 <- d2 %>%
  mutate(county = str_to_lower(county))

# Now they are ready to join! 

join1 <- left_join(d2, or_county)


```


```{r getting map of Oregon}

# helpful link: https://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html


join1 %>%
ggplot() + 
    geom_polygon(aes(long, lat, group = group, fill = avg_self_reg_county)) + 
    coord_fixed(1.3) +
    scale_fill_viridis_c(name = "Score (1-5 scale)", 
                         option = "inferno") +
    labs(title = "Average Self Regulation Scores by County in Oregon",
         caption = "Data from https://www.oregon.gov/ode/educator-resources/assessment/Pages/Kindergarten-Assessment.aspx",
         x = NULL,
         y = NULL) +
     theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        rect = element_blank())

# adjustments that need to be made: 

# label counties 
# adjust plot caption position 
# specify child age, more info on data set 

```

```{r avg self reg by race}

d1 %>%
  filter(stu_grp == "Asian" |
           stu_grp == "White" |
           stu_grp == "Multi-Racial" |
           stu_grp == "Native Hawaiian/Pacific Islander" |
           stu_grp == "Hispanic/Latino" |
           stu_grp == "Black/African American" |
           stu_grp == "American Indian/Alaska Native") %>%
  group_by(stu_grp) %>%
  summarise(avg_self_reg_race = mean(avg_self_reg)) %>%
  ggplot(aes(fct_reorder(stu_grp, avg_self_reg_race), avg_self_reg_race)) +
  geom_point() +
  coord_flip()

```

```{r }

d1 %>%
  filter(stu_grp == "Asian" |
           stu_grp == "White" |
           stu_grp == "Multi-Racial" |
           stu_grp == "Native Hawaiian/Pacific Islander" |
           stu_grp == "Hispanic/Latino" |
           stu_grp == "Black/African American" |
           stu_grp == "American Indian/Alaska Native") %>%
  group_by(county) 

# need to revisit this, how to create a new variable that's the difference between White and Hispanic by county. 
#Thuy: I have a suggestion here: you may want to pivot_wider to get while and hispanic columns, then just subtract one from another

```


```{r average approaches to learning by county over time}

# loading 2013 - 2014 data set 

dfirstwave <- import(here("data", "ka_2013-14_lookback_report.xlsx")) %>%
  clean_names()


dfirstwave1 <- dfirstwave %>%
  rename(county = oregon_kindergarten_assessment,
         district_id = x2,
         district = x3,
         inst_id = x4,
         inst_name = x5,
         inst_type = x6,
         stu_grp_type = x7,
         stu_grp = x8,
         avg_self_reg = x9) %>%
  select(c(1:9))

dfirstwave1 <- dfirstwave1 %>%
  filter(avg_self_reg != "*")

dfirstwave1 = dfirstwave1[-1,]


dfirstwave1$avg_self_reg = as.numeric(dfirstwave1$avg_self_reg)

dfirstwave2 <- dfirstwave1 %>%
  group_by(county) %>%
  summarise(avg_self_reg_county_firstwave = mean(avg_self_reg))

dfirstwave2 <- dfirstwave2 %>%
  mutate(county = str_to_lower(county))

join2 <- left_join(d2, dfirstwave2)

join2 <- join2 %>%
  rename(avg_self_reg_2013 = avg_self_reg_county_firstwave,
         avg_self_reg_2018 = avg_self_reg_county)

join2 <- join2 %>%
  pivot_longer(
    cols = 2:3,
    names_to = "Year", 
    values_to = "Score",
    names_pattern = ".+_.+_.+_(.+)"
  )

join2 %>%
  ggplot(aes(county, Score, color = Year)) +
  geom_point() +
  coord_flip() + 
  geom_line(aes(group = county), color = "gray40", size = 1)+
  labs(title = "Self Regulation Score Changes from 2013 to 2018",
       subtitle = "XXX color denotes increase, YYY color denotes decrease",
       x = NULL,
       y = "Score (on 1-5 scale)")

# Thuy: I have a suggestion here too:  you may want to consider a similar thing we did in homework 1, to create a variable to show whether it's an increase or a decrease in value. eg. mutate(some_name = ifelse(`something' > something, "x", "y")) %>% 

```

